### PR TITLE
Command string-return sending

### PR DESCRIPTION
**Pull request by tech6hutch**
### Description of the PR
Most commands send a message at the end. This PR allows you to return a string (or a string[]) from a command to send it to the relevant channel (or edit the previous message in that channel, if `cmdEditing` is turned on). This works with subcommands, as well.

I changed a few core commands to take advantage of this new feature. However, it may be better to leave the core commands using msg.sendMessage explicitly, so they'd still work if the user disables command string-return sending.

Originally, I modified commandHandler.js directly, but then I decided that making it a finalizer might be better. Users can then easily disable this feature by transferring the finalizer and setting `enabled: false`.

### Changes Proposed in this Pull Request (List new items in CHANGELOG.MD)

- A new finalizer, commandSendReturn.js, which sends the return value from commands, if it's a string or array of strings
- (Possibly) a rewrite of the core commands to take advantage of this feature

### Semver Classification

- [ ] This PR only includes documentation or non-code changes.
- [ ] This PR fixes a bug and does not change the (intended) framework interface.
- [x] This PR adds methods or properties to the framework interface.
- [ ] This PR removes or renames methods or properties in the framework interface.

### CODE REVIEW

**Comment by kyranet** [comment]
The idea of this PR is nice, provides consistency with `throw` (which makes the command exit as a non-successful run and reply the user with whatever the reason is). However, it's quite limited in terms of options, and expanding them may be more expensive.

**Comment by tech6hutch** [comment]
I'll see if I can expand it, without making it too involved to run on every command.

**Comment by bdistin** [comment]
This breaks the consistency that Messages should be returned from Commands; Something that Finalizers and the commandSuccess events inherently expect to get. If this is even used once, this prevents any finalizer from it's previous capability of depending on the sent message.

That's before considering that this only works for content, and only creates extra overhead for commands that you need to send that isn't exclusively content.

Not to mention this is going too far with hand holding.

**Comment by tech6hutch** [comment]
Can this be reopened please? I've changed things, and I think you'll be more pleased with it. It addresses the expected Message return, provides more flexibility to have more than just string content, removes all overhead for the check other than a single object property access, and is opt-in, so users can't rely on hand-holding too much.

**Pull request closed without merging**
