### PR TITLE
Overhaul tutorials

### PR DESCRIPTION
**Pull request by MrJacz**
WIP: Working on updating the Tutorials 👌

### CODE REVIEW

**Comment by MrJacz** [comment]
So the Extendables tutorial is a bit messy, I will add that to the todo list :D

**Comment by MrJacz** [comment]
@bdistin @kyranet Review please :D

**Comment by bdistin** [comment]
If you are going to do that, can you turn those into .md tables instead?

**Comment by MrJacz** [comment]
Sure thing @bdistin

**Comment by MrJacz** [comment]
I will change the package.json back but for now i need to keep it smh

**Comment by MrJacz** [comment]
@bdistin @kyranet Reviews again?

**Comment by monomone** [comment]
I'll probably translate the whole docs to Turkish after this one is finished.

**Comment by MrJacz** [comment]
@KozalakliKozalak That would be really hard considering the docs are generated with JSDoc in English so you would have to like clone klasa and rewrite all the JSDoc for each commit 🤔

**Comment by KozalakliKozalak** [comment]
@MrJacz Welp...

**Comment by tech6hutch** [comment]
Instead of cloning Klasa and modifying the JSDoc, why not just modify the outputted documentation…?

**Comment by MrJacz** [comment]
My suggested way was an idea but what I was trying to explain is its not something easy added

**Comment by MrJacz** [comment]
Review when? ☹️

**Pull request merged**
