### PR TITLE
Fix spelling/grammar

### PR DESCRIPTION
**Pull request by DudeVoid**
### Description of the PR
This PR updates the spelling and grammatical errors in the README.

### Changes Proposed in this Pull Request (List new items in CHANGELOG.MD)

- I've corrected the spelling. (croation -> Croatian).

### Semver Classification

- [x] This PR only includes documentation or non-code changes.
- [ ] This PR fixes a bug and does not change the (intended) framework interface.
- [ ] This PR adds methods or properties to the framework interface.
- [ ] This PR removes or renames methods or properties in the framework interface.

### CODE REVIEW

**Comment by DudeVoid** [comment]
That was fast. kek

**Comment by MrJacz** [comment]
We have a discord server with the GitHub webhooks setup quick easy to see updates 👍

**Comment by DudeVoid** [comment]
Okay.

**Comment by QuantumlyTangled** [comment]
Might also make komada lowercase seeing how klasa is lower case.

**Comment by DudeVoid** [comment]
?

**Comment by DudeVoid** [comment]
Huh.

**Pull request merged**
