### PR TITLE
Translate help command (fr and de)

### PR DESCRIPTION
**Pull request by Pandraghon**
@pedall or @dada1134 can you review the de-DE part, please ?

### CODE REVIEW

**Comment by Pandraghon** [comment]
Erm... should this PR be merged into SettingGateway-Rewrite instead?

**Comment by kyranet** [comment]
I don't know, but it seems nothing else will be added to 0.4.0-dev to avoid merge conflicts in 0.5.0-dev.

**Comment by Pandraghon** [comment]
The SGv2 language part is already ahead of 0.5.0-dev

**Comment by bdistin** [comment]
This should be re-targeted to v0.5.0-dev and the klasa-pieces repo pls.

**Pull request closed without merging**
