### PR TITLE
typings: Mark Task#run's return type as unknown

### PR DESCRIPTION
**Pull request by Skillz4Killz**
### Description of the PR
This PR allows you to return anything from a task. It is really annoying to be forced to return void in tasks. In every one of my files when I want to cancel something I always do `return null` but in the tasks, I am being forced to do `return`. Forcing a return void destroys consistency across my bot.

Also, the fact that I can't just end the task like
```js
return this.client.emit('log', 'x task ran successfully')
```

But instead, have to do
```js
this.client.emit('log', 'x task ran successfully')
return
```

```js
Property 'run' in type 'default' is not assignable to the same property in base type 'Task'.
  Type '() => Promise<boolean | void>' is not assignable to type '(data: any) => Promise<void>'.
    Type 'Promise<boolean | void>' is not assignable to type 'Promise<void>'.
      Type 'boolean | void' is not assignable to type 'void'.
        Type 'false' is not assignable to type 'void'.ts(2416)
```

### Changes Proposed in this Pull Request (List new items in CHANGELOG.MD)

- Promise<void> => Promise<any>

### Semver Classification

- [ ] This PR only includes documentation or non-code changes.
- [ ] This PR fixes a bug and does not change the (intended) framework interface.
- [ ] This PR adds methods or properties to the framework interface.
- [ ] This PR removes or renames methods or properties in the framework interface.

### CODE REVIEW

**Comment by tech6hutch** [comment]
What's the use case for returning something from Task#run? Running tasks manually?

**Comment by Skillz4Killz** [comment]
```js
if (somecheck) {
  this.client.emit(`log`, `explain why it was cancelled`)
  return
}
```

As opposed to

```js
if (somecheck) return this.client.emit(`log`, `explian why it was cancelled`)

**Comment by kyranet** [comment]
In that case, the return type should be `unknown`, as it'll act like a rubbish bin type

**Comment by Skillz4Killz** [comment]
Do you mean it should return Promise <unknown>

**Comment by tech6hutch** [comment]
Promise<unknown>

**Comment by tech6hutch** [comment]
Whoa, GitHub eats the part in less-than greater-than signs. `Promise<unknown>`

**Comment by kyranet** [comment]
`Promise<unknown>` and `unknown` differ that in one the promise is required, and the other can be a promise, can be a string, can be a Tesla Roadster, can be anything, since it's unknown.

It's a type implemented in TypeScript 3.2.0 that can be casted to everything.

**Comment by Skillz4Killz** [comment]
@bdistin was this closed accidentally without merging or did you have a good reason to close this? I thought i gave a pretty good use case for this change.

**Comment by bdistin** [comment]
the change is already in alpha

**Pull request closed without merging**
