### PR TITLE
Fix `RichMenu#run()` return value type

### PR DESCRIPTION
**Pull request by KenanY**
`RichMenu#run()` returns the same type as `RichDisplay#run()`, which is
a `Promise<ReactionHandler>`.

### CODE REVIEW

**Comment by kyranet** [comment]
Can you merge #92 with this one? No need to make multiple PRs if you can merge them in one. If you need time to find all the bugs, let me know and I'll put a WIP label to this PR.

**Comment by KenanY** [comment]
Sure thing! I did multiple PRs since the changes are more-or-less unrelated :)

**Comment by kyranet** [comment]
No worries! Just trying to organize the PRs a little so they don't become a mess :)

**Comment by KenanY** [comment]
All right, these three changes are all I have for the time being :) I can squash them together if desired.

**Comment by kyranet** [comment]
Despite of nothing in JS being able to be private, but protected (by following the name conventions), we do use all these kinds of methods as `@private`. Nonetheless once [tc39/proposal-class-fields](https://github.com/tc39/proposal-class-fields) gets implemented, we may update many things to make them actually private. It's just, _a matter of time_,

**Comment by KenanY** [comment]
Remaining typescript errors are (using `master` of both discord.js and klasa):

```
node_modules/klasa/typings/index.d.ts(26,3): error TS2305: Module ''discord.js'' has no exported member 'OAuth2Application'.
node_modules/klasa/typings/index.d.ts(31,3): error TS2305: Module ''discord.js'' has no exported member 'Attachment'.
node_modules/klasa/typings/index.d.ts(32,3): error TS2305: Module ''discord.js'' has no exported member 'RichEmbed'.
node_modules/klasa/typings/index.d.ts(33,3): error TS2305: Module ''discord.js'' has no exported member 'RichEmbedOptions'.
node_modules/klasa/typings/index.d.ts(178,29): error TS8020: JSDoc types can only be used inside documentation comments.
```

Dunno if they're worth fixing, since they're not based on a released discord.js version yet. (Also haven't yet figured out the last one regarding JSDoc 🤔 )

**Comment by MrJacz** [comment]
I've noticed these errors and stated this to Kyra... problem is the discord.js@master typings are for stable so the Discord.js errors are bound to happen until they're updated and the JSDoc I couldn't work out either.

**Comment by kyranet** [comment]
At the moment of writting the typings, only 11.2.0 typings were available, and I had to work with them (RichEmbed instead of EmbedMessage, and so on). If `MessageEmbed` is now available, then I'd be happy if you could update them 👍

**Comment by MrJacz** [comment]
I've heard the Discord.js typings have been updated but I have not checked for myself

**Comment by bdistin** [comment]
Can you also allow edits from maintainers. This will not be merged if this branch is out-of-date with master, and without permission, I cannot automatically merge the branch to let CI re-run.

**Comment by KenanY** [comment]
@bdistin Enabled.

**Comment by bdistin** [comment]
Ok, I have been discussing protected vs private with some of the others. I pulled your branch and built docs. jsdocs#protected makes those methods show up on the docs site. I don't want them to be _that_ public, however, I am fine with the typescript definitions to refer to them as protected so that you can properly extend them with TS.

So, can we revert the jsdoc references to private, and we can keep the ts definitions as protected?

**Comment by KenanY** [comment]
@kyranet Updated, PTAL.

@bdistin Reverted that change :)

**Comment by kyranet** [comment]
They show up as `protected` yet, but thanks for the typings update 👍

**Pull request merged**
