### PR TITLE
Lord of mistakes

### PR DESCRIPTION
**Pull request by MrJacz**
### Changes Proposed in this Pull Request (List new items in CHANGELOG.MD)
Fixes mistake in Client.js line 370 this.config not this.configs
-

### Semver Classification

- [ ] This PR only includes documentation or non-code changes.
- [ x] This PR fixes a bug and does not change the (intended) framework interface.
- [ ] This PR adds methods or properties to the framework interface.
- [ ] This PR removes or renames methods or properties in the framework interface.

### CODE REVIEW

**Comment by MrJacz** [comment]
Ao is too fast lmfao

**Comment by MrJacz** [comment]
Fixing default bug two sec

**Comment by bdistin** [comment]
img

**Comment by MrJacz** [comment]
Because you too fast lmfao

**Pull request closed without merging**
