### PR TITLE
docs: Fixed ReactionHandler time descriptions

### PR DESCRIPTION
**Pull request by tech6hutch**
### Description of the PR
~Collector, which ReactionCollector extends, which ReactionHandler extends, has a `time` option, but it doesn't set it as a property. ReactionHandler sets this as a property, and attempts to set a default time, but it won't do any good after `super()` has already run, since Collector has already set the timeout based on `options.time` and not a property. In addition, this (attempted) default was not documented. This PR corrects these things.~

I fix doc.

### Changes Proposed in this Pull Request (List new items in CHANGELOG.MD)

- Fix doc

### Semver Classification

- [X] This PR only includes documentation or non-code changes.
- [ ] This PR fixes a bug and does not change the (intended) framework interface.
- [ ] This PR adds methods or properties to the framework interface.
- [ ] This PR removes or renames methods or properties in the framework interface.

### CODE REVIEW

**Comment by bdistin** [comment]
Although the docs are wrong, that's not what this.time is for... see pr #57

**Comment by tech6hutch** [comment]
Oh, my apologies. I will fix that.

**Comment by tech6hutch** [comment]
@bdistin I corrected my (in)corrections. This is probably out of scope for this PR, but would you support renaming the property from `time` to something like `menuTime`? The current name is misleading, especially for people who haven't used the Discord.js ReactionCollector before and might assume, from the name, that this option is used for general collector timeout.

**Comment by bdistin** [comment]
docs still wrong, this.time is used in the jump menu prompt

**Pull request merged**
