### PR TITLE
Info cmd text

### PR DESCRIPTION
**Pull request by tech6hutch**
* Corrected async/await bullet (it's ES8, not ES7)
* Corrected the sentence that said you can download commands (Klasa doesn't have that 😛)
* Made capitalization, style, and consistency improvements
* Added/corrected wording
* Added emojis for readability and "coolness" (I can remove these if not desired)
* I attempted to port the ES8 and no-downloading changes to the other languages; I don't speak any of them, so I'm sorry if there are any errors

### CODE REVIEW

**Comment by tech6hutch** [comment]
Shite, this has the eval changes. Fixing.

**Comment by tech6hutch** [comment]
I fixed the eval stuff, but why are the `@since` tags in Util showing as changed? I copy-pasted from master.

**Comment by tech6hutch** [comment]
@kyranet can you check the Spanish, please?

**Comment by bdistin** [comment]
Turkish and Italian have been merged. When you get a moment, could you give them the same treatment?

**Comment by bdistin** [comment]
This should be re-targeted to v0.5.0-dev and the klasa-pieces repo pls.

**Comment by CyberiumShadow** [comment]
On the 5th day of christmas, my github gave to me, 6 notifcations, 5 Broken Languages, 4 requested changes, 3 dirigeant devs, 2 discord frameworks, 1 Merged PR.

(COnflict Fixes in Progress)

**Comment by bdistin** [comment]
This pr is equally fucked up... New branch, copy changes, new pr from new branch.

**Comment by tech6hutch** [comment]
As discussed in the server, I will copy this to a new branch

en-US to master, the others to the pieces repo. And I'll make the modifications the new languages, as well

**Pull request closed without merging**
