### PR TITLE
Edited invite (it was invalid)

### PR DESCRIPTION
**Pull request by ndr3w221**
I copied the invite from klasa.js.org

### CODE REVIEW

**Comment by QuantumlyTangled** [comment]
This wont work as the invite there gets regenerated each time you click the button and only has one use

**Comment by kyranet** [comment]
It's actually invalid, the invites generated by the website only last 5 minutes and limited to one user. This should have other description but not sure what.

cc @bdistin

**Comment by UnseenFaith** [comment]
Should just remove this line or link back to our website.

**Comment by bdistin** [comment]
What @UnseenFaith said

**Pull request closed without merging**
