### PR TITLE
Translate en-US to it-IT (Italian)

### PR DESCRIPTION
**Pull request by HellPie**
Added italian localization, which I needed for a server of mine, thought I would share.

### CODE REVIEW

**Comment by HellPie** [comment]
I noticed there are a couple instances where in en-US double quotes are used, should I change those in en-US and possibly other langs or should I used them in it-IT?

**Comment by bdistin** [comment]
I am not exactly sure what I am going to do with this. I am currently considering moving all languages but English to the pieces repo.

**Comment by HellPie** [comment]
if you want I can open a new pr to the pieces repo, just let me know

**Comment by bdistin** [comment]
All languages are going to be merged in for the v0.4.0 release, but in v0.5.0 languages other than english will be moved to the pieces repo and maintained from there.

**Pull request merged**
