### PR TITLE
Fix RichMenu empty page and typings

### PR DESCRIPTION
**Pull request by HellPie**
There is always an empty page added due to the inclusion of just added options to the count of missing options to add, plus the typings for a RichMenu option suggested "description" instead of "body".

### CODE REVIEW

**Comment by bdistin** [comment]
There are several other instances of description -> body s that need to be fixed

**Comment by HellPie** [comment]
Weird. I thought that was the only object defining RichMenu options.

**Comment by bdistin** [comment]
See like: https://github.com/dirigeants/klasa/blob/master/tutorials/names.json#L42 It creates a section at the bottom that says Further Reading. With the appropriate links. The child page then would only include information on how it extends the parent/what's the same, whats different/and examples without repeating a lot of what's already written/the same in the parent class.

**Comment by bdistin** [comment]
still waiting on the line 41 fix

**Pull request merged**
