### PR TITLE
Make Store.walk() resolve '.ts' files as well

### PR DESCRIPTION
**Pull request by jdenderplays**
### Description of the PR
Stores walk their dictionaries and load all '.js' files as pieces. This pull request make them load '.ts' files as well.

### Changes Proposed in this Pull Request (List new items in CHANGELOG.MD)
- Patch Store to load '.ts' files

### Semver Classification
Minor patch

- [ ] This PR only includes documentation or non-code changes.
- [x] This PR fixes a bug and does not change the (intended) framework interface.
- [ ] This PR adds methods or properties to the framework interface.
- [ ] This PR removes or renames methods or properties in the framework interface.

### CODE REVIEW

**Comment by MrJacz** [comment]
You compile TS to JS, you don't run typescript you compile it.

**Comment by kyranet** [comment]
You cannot run `.ts` files in native Node.js, you need to compile them first.

**Comment by jdenderplays** [comment]
This was intended to add support to various typescript hooks, not vanilla node. (i.e. ts-node or typescript-require)

**Comment by ShayBox** [comment]
Should be implemented, very useful.
ts-node is nicer than having to compile.

**Comment by ShayBox** [comment]
Why do you need a plugin for this, just merge the pr for people that use node registers for .ts extensions.

This doesn't impact non-ts users at all, non ts users wont have .ts files in their folders, and if you're worried about that, add a check to see if they're using a node register.

I'm tired of waiting a minute for my bot to compile every time I save.

**Comment by kyranet** [comment]
1. The repository has been deleted, I can't reopen this PR, let alone merging it.
1. The check is flawed, it should check it's not a `.d.ts` file, which may be present in JS projects (like mine).
1. Registering `.ts` natively in klasa implies we need `ts-node` bundled as one of our dependencies.
1. This should be `Object.keys(require.extensions).filter(key => key !== '.json' && key !== '.node');`, then filter files that are in those extensions. This way, when `ts-node` is present, `.ts` will be added to `require.extensions`, therefore loaded.

**Pull request closed without merging**
