### PR TITLE
Add: prefixCaseInsensitive client option

### PR DESCRIPTION
**Pull request by AdityaTD**
### Description of the PR
This PR adds a client option to toggle the prefix's case sensitivity.

### Changes Proposed in this Pull Request (List new items in CHANGELOG.MD)
-

### Semver Classification

- [ ] This PR only includes documentation or non-code changes.
- [ ] This PR fixes a bug and does not change the (intended) framework interface.
- [x] This PR adds methods or properties to the framework interface.
- [ ] This PR removes or renames methods or properties in the framework interface.

### CODE REVIEW

**Comment by bdistin** [comment]
There is a better way to implement this. When I get to a workstation, I will give more details

**Comment by kyranet** [comment]
This should only edit this line:

https://github.com/dirigeants/klasa/blob/master/src/monitors/commandHandler.js#L75

And add `, 'i'` to allow insensitive-case check.

**Comment by bdistin** [comment]
half of the right answer^

**Comment by AdityaTD** [comment]
Oh I see what you mean, that's honestly a much efficient way.

**Pull request merged**
