### PR TITLE
Update en-US.js

### PR DESCRIPTION
**Pull request by Cinegez**
Missing translation for COMMAND_UNLOAD

### CODE REVIEW

**Comment by Pandraghon** [comment]
It's just a typo : https://github.com/Cinegez/klasa/blob/c954395cd066829e608ced6d5ae0e8ea87c8556a/src/languages/en-US.js#L48 (the current key is `COMMAD_UNLOAD`)

**Comment by bdistin** [comment]
Please fix line 48 instead of duplicating the code.

**Comment by bdistin** [comment]
Still waiting on my above comment.

**Comment by kyranet** [comment]
I have fixed the typo so this PR can be merged.

**Pull request merged**
