### PR TITLE
toLowerCase the command name

### PR DESCRIPTION
**Pull request by Pandraghon**
Because of https://github.com/dirigeants/klasa/blob/b6df5b58161d9335412801559ec3c3af1594a159/src/monitors/commandHandler.js#L30
lower

### CODE REVIEW

**Comment by bdistin** [comment]
```javascript
this.name = options.name || file[file.length - 1].slice(0, -3).toLowerCase();
```
options.name and any element of options.aliases being anything but lowercase is framework user (dev) error. Willing to concede in letting filenames not be all lowercase, but that also leads to the possibility of some unexpected supercedence when you have two commands test.js and Test.js, as depending on which one loads last, either or might be loaded.

Additionally, double check the creating commands tutorial, and ensure there is a note saying that command names and aliases must be lowercase

**Comment by tech6hutch** [comment]
Not only does the creating commands tutorial not mention that names must be lowercase, but the example command it gives has a name with uppercase (`'yourCommandName'`).

If this is supposed to be user error, it should throw if you try to name a command with an uppercase letter, imo. It's unintuitive otherwise.

**Comment by bdistin** [comment]
Wasting processing asserting that the dev correctly configures commands to work with the included commandHandler monitor (not even what someone else might prefer), is just as wasteful as correcting the input to the bias of our commandHandler monitor.

It should be mentioned in the tutorial though. (lowercase no spaces)

**Comment by Pandraghon** [comment]
So... just : 
```js
this.name = options.name || file[file.length - 1].slice(0, -3).toLowerCase();
```

The VSC extension should have a note about that too

**Comment by tech6hutch** [comment]
I meant checking up front, when commands are loaded (not run), if the name contains any capital letters. I can't imagine that would take up much processing power.

Not a big deal, of course; it would just help reinforce the requirement.

**Pull request merged**
